name: salon_finder
description: "A saloon finding application for aamusted students"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  persistent_bottom_nav_bar: ^6.2.1
  geocoding: ^4.0.0
  country_code_picker: ^3.3.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  http: ^1.5.0
  pay_with_paystack:
    git:
      url: 'https://github.com/Emmanuelfrimpong/pay_with_paystack.git'
  url_launcher: ^6.3.2
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/


flutter_native_splash:
  color: "#ffffff" # The background color of the splash screen.  It can be any valid color.
  image: assets/images/logo_black.png
  android: true
  ios: true
  web: true
  color_web: "#ffffff" # The background color of the splash screen for web.  It can be any valid color.
  image_web: assets/images/icon_black.png
  # dart run flutter_native_splash:create

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_black.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon_black.png"
    background_color: "#ffffff" # The background color of the web app icon. It can be any valid color.
  
  # dart run flutter_launcher_icons