// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjfxFnDtmqh-PDYJhIj5hDw_dTuM_6tg4',
    appId: '1:784933587810:web:d886ec35144f5393597a3b',
    messagingSenderId: '784933587810',
    projectId: 'salon-finder-p',
    authDomain: 'salon-finder-p.firebaseapp.com',
    storageBucket: 'salon-finder-p.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiPk6EXbcA81cWpiChrk3M2psTo0Jp8CI',
    appId: '1:784933587810:android:541c126b04c926a6597a3b',
    messagingSenderId: '784933587810',
    projectId: 'salon-finder-p',
    storageBucket: 'salon-finder-p.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJXz6UrV1ThBFoEKrBoCySNynn5FYVYng',
    appId: '1:784933587810:ios:2447c6e5bc828ec7597a3b',
    messagingSenderId: '784933587810',
    projectId: 'salon-finder-p',
    storageBucket: 'salon-finder-p.firebasestorage.app',
    iosBundleId: 'com.fihankra.salonFinder',
  );
}
